# SPDX-FileCopyrightText: 2020-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-FileCopyrightText: 2020-2023 Stefan Niedermann <info@niedermann.it>
# SPDX-License-Identifier: GPL-3.0-or-later
# These are supported funding model platforms

custom: https://nextcloud.com/include/
